theme: jekyll-theme-midnight
title: Schwarzsilber
description:
excerpt_separator: <!--more-->
show_downloads: false
google_analytics: false
lang: de-DE
#PWA
background_color: #252525
theme_color: #252525
