timezone: Europe/Berlin
lang: de-DE
title: Schwarzsilber
description:
excerpt_separator: <!--more-->
show_downloads: false
google_analytics: false
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "default"
      author: "Kolya"
  -
    scope:
      path: "css"
    values:
      layout: "none"
kramdown:
  input: GFM
  hard_wrap: true
gems:
  - jekyll-last-modified-at
#PWA
background_color: #252525
theme_color: #252525
