timezone: Europe/Berlin
lang: de-DE
date_format: "%A, %d.%B %Y, %R"
day_format: "%A, %d.%B %Y"
title: Schwarzsilber
description:
excerpt_separator: <!--more-->
show_downloads: false
google_analytics: false
include: [_resources]
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "default"
      author: "Kolya"
  -
    scope:
      path: "css"
    values:
      layout: "none"
kramdown:
  input: GFM
  hard_wrap: true
#PWA
background_color: #252525
theme_color: #252525
plugins:
  - jekyll-seo-tag
